language: cpp
os:
 - linux
sudo: false
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
      # The cmake Travis has doesn't like the add_executable line.
      # This is the fix I found.
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

script:
 - mkdir build
 - pushd build
 - cmake .. -DCMAKE_BUILD_TYPE=RELEASE || exit 1
 - cmake --build . -- -j2 || exit 1
 - popd
 - cp build/lily .
 - python ./pre-commit-hook.py --verbose || exit 1
